Repository aers/FFXIVClientStructs, pull requests merged in 2023-09, with the labels that each got.

#527 Add .editorconfig
  .editorconfig
Labels: enhancement

#549 Add some graphics structs, fields and functions
  FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/ConstantBuffer.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Device.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/ShaderPackage.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Kernel/Texture.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Render/Material.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Render/Model.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterUtility.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Human.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Object.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Scene/ResidentResourceManager.cs
  FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/MaterialResourceHandle.cs
  FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ResourceHandle.cs
  FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ShaderPackageResourceHandle.cs
  FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/TextureResourceHandle.cs
  FFXIVClientStructs/FFXIV/Shader/CameraParameter.cs
  FFXIVClientStructs/FFXIV/Shader/CommonParameter.cs
  FFXIVClientStructs/FFXIV/Shader/CustomizeParameter.cs
  FFXIVClientStructs/FFXIV/Shader/InstanceParameter.cs
  FFXIVClientStructs/FFXIV/Shader/ModelParameter.cs
  FFXIVClientStructs/FFXIV/Shader/SceneParameter.cs
Labels: new system

#564 Add AddonDTR
  FFXIVClientStructs/FFXIV/Client/UI/AddonDtr.cs
Labels: new system

#568 Add info to InfoProxyItemSearch (MarketBoard)
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxy11.cs
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyInterfaces.cs
  ida/data.yml
Labels: updated structure

#569 Add AddonActionMenu
  FFXIVClientStructs/FFXIV/Client/UI/AddonActionMenu.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
  ida/data.yml
Labels: new system

#572 Add GroupManager_GetNextInstance
  FFXIVClientStructs/FFXIV/Client/Game/Group/GroupManager.cs
  ida/data.yml
Labels: new system

#584 Small extras from opcode removal
  FFXIVClientStructs/FFXIV/Application/Network/WorkDefinitions/EnterContentInfo.cs
  FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/PublicContentDirector.cs
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxy11.cs
  ida/data.yml
Labels: updated structure

#580 Fix AddonLookingForGroupDetail
  FFXIVClientStructs/FFXIV/Client/UI/AddonLookingForGroupDetail.cs
Labels: updated structure

#567 fix Show/Hide vfuncs in AtkUnitBase
  FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitBase.cs
Labels: breaking change, updated structure

#571 InfoProxyItemSearch -> InfoProxyCatalogSearch; InfoProxy11 -> InfoPro…
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxy11.cs
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCatalogSearch.cs
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyItemSearch.cs
Labels: breaking change

#563 Friendslist cleanup
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFriendList.cs
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCommonList.cs
Labels: breaking change, updated structure

#562 Update RaptureGearsetModule
  FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureGearsetModule.cs
  ida/data.yml
Labels: breaking change, updated structure

#552 Fix DirectionalLighting Angle types
  FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaViewPortrait.cs
Labels: breaking change, updated structure

#504 Use FixedSizeArray in RaptureMacroModule
  FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs
Labels: breaking change, updated structure

#582 FixedSizeArray cleanup
  FFXIVClientStructs/FFXIV/Client/Game/QuestManager.cs
  FFXIVClientStructs/FFXIV/Client/Game/RetainerManager.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRetainerList.cs
  FFXIVClientStructs/FFXIV/Client/UI/Misc/RetainerCommentModule.cs
Labels: breaking change

#503 Label parts of AddonRecipeNote
  FFXIVClientStructs/FFXIV/Client/UI/AddonRecipeNote.cs
Labels: breaking change, updated structure

#501 Replace property Instance accessor with method
  FFXIVClientStructs/FFXIV/Client/Game/Control/CameraManager.cs
  FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureMacroModule.cs
  FFXIVClientStructs/FFXIV/Client/UI/Shell/RaptureShellModule.cs
Labels: breaking change

#426 Update AtkUnitList
  FFXIVClientStructs/FFXIV/Component/GUI/AtkUnitList.cs
Labels: breaking change

#507 Fix ResourceHandle memory layout for SqPack file identification
  FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ResourceHandle.cs
  FFXIVClientStructs/FFXIV/Client/System/Resource/ResourceGraph.cs
Labels: breaking change, updated structure

#423 Fix MoveItemSlot parameter types
  FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
Labels: breaking change

#454 Add AgentGettersGenerator
  FFXIVClientStructs.InteropSourceGenerators/AgentGettersGenerator.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentActionMenu.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentAozContentResult.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentArchiveItem.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerEditor.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerMIP.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerParty.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCharaCard.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentChatLog.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCompanyCraftMaterial.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContext.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCraftActionSimulator.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentDeepDungeonInspect.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentDeepDungeonMap.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentDeepDungeonStatus.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentExplorationResult.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFreeCompany.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFreeCompanyCrestEditor.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFreeCompanyProfile.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFriendList.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGatheringNote.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGcArmyExpedition.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentGrandCompanySupply.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHousingPlant.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentHudLayout.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentIKDFishingLog.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentIKDResult.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentInspect.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentInventoryContext.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemDetail.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentItemSearch.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLoot.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMJIPouch.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMap.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismMiragePlate.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismPrismBox.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMiragePrismPrismItemDetail.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentModule.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMonsterNote.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMycItemBox.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentReadyCheck.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRecipeNote.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRequest.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRetainerList.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRetainerTask.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentRevive.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentSalvage.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentScenarioTree.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentShop.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentTeleport.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentTryon.cs
Labels: breaking change

#421 Added AgentMycBattleAreaInfo.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMycBattleAreaInfo.cs
Labels: new system, requested changes

#601 QuestLinkMarkers
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentMap.cs
Labels: new system, requested changes
