Repository aers/FFXIVClientStructs, pull requests merged in 2023-08, with the labels that each got.

#551 Create CExporter action
  .github/workflows/cexporter.yaml
  .github/workflows/struct-update.yaml
Labels: enhancement

#553 Add some documentation for exdgetters
  ida/README.md
Labels: documentation

#525 Add some functions related to mounts and ornaments.
  FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
  FFXIVClientStructs/FFXIV/Client/Game/Character/Ornament.cs
  ida/data.yml
Labels: updated structure

#505 Add reaper shroud container.
  FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
  ida/data.yml
Labels: new system, updated structure
