Repository aers/FFXIVClientStructs, pull requests merged in 2023-10, with the labels that each got.

#422 Ghidra Getting Started
  Ghidra/Common Issues.md
  Ghidra/Getting Started.md
  Ghidra/images/Address Dalamud Example.png
  Ghidra/images/Analysis Summary.png
  Ghidra/images/Analyze In Progress.png
  Ghidra/images/Analyze Options.png
  Ghidra/images/Analyze.png
  Ghidra/images/Enum Size.png
  Ghidra/images/Framework After.png
  Ghidra/images/Framework Before.png
  Ghidra/images/Import Results Summary.png
  Ghidra/images/Import.png
  Ghidra/images/Manage Script Directories.png
  Ghidra/images/Misaligned Struct.png
  Ghidra/images/Open Script Manager.png
  Ghidra/images/Parse C Source.png
  Ghidra/images/Project Window Multi.png
  Ghidra/images/Project Window.png
  Ghidra/images/Script Manager Add Directory.png
  Ghidra/images/User Scripts.png
  Ghidra/scripts/SigScanner.java
  Ghidra/scripts/ffxiv_exdgetters.java
Labels: documentation

#631 Update Forced Wetness flag and a bunch of DrawDataContainer stuff.
  FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
  FFXIVClientStructs/FFXIV/Client/Game/Character/DrawDataContainer.cs
Labels: requested changes

#657 UIInputData fixes and improvements
  FFXIVClientStructs/FFXIV/Client/UI/UIInputData.cs
Labels: updated structure

#653 Updates to Hotbar structs
  FFXIVClientStructs/FFXIV/Client/UI/AddonActionBarCross.cs
Labels: updated structure

#652 Fix HotbarShareStateBitmask offset for 6.5
  FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureHotbarModule.cs
Labels: updated structure

#556 Patch 6.5 remove all obsoletes in current code
  FFXIVClientStructs/CExportIgnore.cs
  FFXIVClientStructs/FFXIV/Client/Game/Character/BattleChara.cs
  FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
  FFXIVClientStructs/FFXIV/Client/Game/Character/CharacterManager.cs
  FFXIVClientStructs/FFXIV/Client/Game/Character/DrawDataContainer.cs
  FFXIVClientStructs/FFXIV/Client/Game/Housing/HousingManager.cs
  FFXIVClientStructs/FFXIV/Client/Game/Housing/HousingWorkshopTerritory.cs
  FFXIVClientStructs/FFXIV/Client/Game/InstanceContent/InstanceContentDirector.cs
  FFXIVClientStructs/FFXIV/Client/Game/MJI/IslandState.cs
  FFXIVClientStructs/FFXIV/Client/Game/SavedAppearanceManager.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/Cabinet.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/ContentsFinder.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/Inspect.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/MobHunt.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/WeaponState.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Environment/EnvManager.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Scene/CharacterBase.cs
  FFXIVClientStructs/FFXIV/Client/Graphics/Scene/Human.cs
  FFXIVClientStructs/FFXIV/Client/System/Resource/Handle/ResourceHandle.cs
  FFXIVClientStructs/FFXIV/Client/UI/AddonContextMenu.cs
  FFXIVClientStructs/FFXIV/Client/UI/AddonFateReward.cs
  FFXIVClientStructs/FFXIV/Client/UI/AddonJournalDetail.cs
  FFXIVClientStructs/FFXIV/Client/UI/AddonWeeklyBingo.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCharaCard.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContext.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentFreeCompany.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentLobby.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentScreenLog.cs
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCrossRealm.cs
  FFXIVClientStructs/FFXIV/Client/UI/Misc/CharaView.cs
  FFXIVClientStructs/FFXIV/Client/UI/Misc/ConfigModule.cs
  FFXIVClientStructs/FFXIV/Client/UI/Misc/ItemOrderModule.cs
  FFXIVClientStructs/FFXIV/Client/UI/RaptureAtkModule.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkArrayData.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkCursor.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkImageNode.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkLinkedList.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkResNode.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkTextNode.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkTexture.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkTextureResource.cs
  FFXIVClientStructs/FFXIV/Component/GUI/AtkUldManager.cs
  FFXIVClientStructs/Interop/Resolver.cs
Labels: breaking change, updated structure

#645 Remove Incorrect Map Structs
  FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs
Labels: breaking change

#667 Update InfoModule
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoModule.cs
  ida/data.yml
Labels: new system

#661 Add GcArmyManager
  FFXIVClientStructs/FFXIV/Client/Game/GcArmyManager.cs
  ida/data.yml
Labels: new system, requested changes

#663 Update InventoryManager
  FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
  ida/data.yml
Labels: new system

#658 Update AddonRepair for 6.5
  FFXIVClientStructs/FFXIV/Client/UI/AddonRepair.cs
Labels: updated structure, requested changes

#675 add mount passenger CharacterMode
  FFXIVClientStructs/FFXIV/Client/Game/Character/Character.cs
Labels: updated structure

#656 Add InventoryType.ReconstructionBuyback
  FFXIVClientStructs/FFXIV/Client/Game/InventoryManager.cs
Labels: updated structure

#665 Add AddonConfig
  FFXIVClientStructs/FFXIV/Client/UI/Misc/AddonConfig.cs
  FFXIVClientStructs/FFXIV/Client/UI/UIModule.cs
Labels: breaking change

#683 Add AgentCrossWorldLinkshell.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCrossWorldLinkshell.cs
Labels: new system

#684 Update Map
  FFXIVClientStructs/FFXIV/Client/Game/UI/Map.cs
  ida/data.yml
Labels: updated structure

#677 Update AgentBannerEditor
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentBannerEditor.cs
  ida/data.yml
Labels: updated structure

#654 More PlayerState/UIState findings
  FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
  FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs
  ida/data.yml
Labels: updated structure

#673 Update SatisfactionSupplyManager
  FFXIVClientStructs/FFXIV/Client/Game/SatisfactionSupplyManager.cs
Labels: breaking change

#669 Update some structs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentCharaCard.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContentsFinder.cs
  FFXIVClientStructs/FFXIV/Client/UI/Agent/AgentContext.cs
  FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyCommonList.cs
  FFXIVClientStructs/FFXIV/Client/UI/Misc/RaptureLogModule.cs
Labels: breaking change

#655 Fix PlayerState aetheryte id field types
  FFXIVClientStructs/FFXIV/Client/Game/UI/PlayerState.cs
Labels: breaking change
